COLUMNS : 
data = [
  {'CUST_ID': 0, 
   'BALANCE': 8950.0,
   'BALANCE_FREQUENCY': 8950.0,
   'PURCHASES': 8950.0,
   'ONEOFF_PURCHASES': 8950.0,
   'INSTALLMENTS_PURCHASES': 8950.0,
   'CASH_ADVANCE': 8950.0,
   'PURCHASES_FREQUENCY': 8950.0,
   'ONEOFF_PURCHASES_FREQUENCY': 8950.0,
   'PURCHASES_INSTALLMENTS_FREQUENCY': 8950.0,
   'CASH_ADVANCE_FREQUENCY': 8950.0,
   'CASH_ADVANCE_TRX': 8950.0,
   'PURCHASES_TRX': 8950.0,
   'CREDIT_LIMIT': 8949.0,
   'PAYMENTS': 8950.0, 
   'MINIMUM_PAYMENTS': 8637.0,
   'PRC_FULL_PAYMENT': 8950.0,
   'TENURE': 8950.0},
  # Add remaining dictionary objects 
]