# Config file for ML project stages and artifact locations 
artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Krish-Goyani/DataSets/raw/main/archive%20(2).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir:   artifacts/data_ingestion/CC GENERAL.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation_and_clustering:
  root_dir: artifacts/data_transformation_and_clustering
  data_path: artifacts/data_ingestion/CC GENERAL.csv
  metrics_file_name: artifacts/data_transformation_and_clustering/metrics.json

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation_and_clustering/train.csv
  test_data_path: artifacts/data_transformation_and_clustering/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation_and_clustering/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json